### ISSUE TITLE
Hi!

### ISSUE THREAD

**Issue by smileycreations15** [Nambaseking01/nambaseking01.github.io#1]
Hi! I made a wiki :D https://wiki.smileycreations15.com/index.php?title=Main_Page

**Comment by Nambaseking01** [comment]
Oh wow! Great job! 👍 

Anyways, I am currently working on the kids activities website for mine.

**Comment by Nambaseking01** [comment]
> Hi! I made a wiki :D https://wiki.smileycreations15.com/index.php?title=Main_Page

Sorry for not replying, I just found out how to.

**Comment by smileycreations15** [comment]
@Nambaseking01 That is ok, I would want you to join :)))

**Comment by Nambaseking01** [comment]
@smileycreations15 To what should should I have the pleasure of joining? :)

**Comment by Nambaseking01** [comment]
@smileycreations15 Oh, you mean your Wiki. I joined it alright. :D

**Comment by smileycreations15** [comment]
@Nambaseking01 There are scratch tutorials too

**Comment by Nambaseking01** [comment]
@smileycreations15 Where?

**Comment by smileycreations15** [comment]
@Nambaseking01 in my wiki

**Comment by smileycreations15** [comment]
@Nambaseking01 there will be other topics too

**Comment by smileycreations15** [comment]
Add `[[Category:Scratch]]` at the end of each tutorial

**Comment by smileycreations15** [comment]
@Nambaseking01 Also add `;` at the end of `&#x263A`

**Comment by Nambaseking01** [comment]
@smileycreations15 I cannot find any tutorials in your Wiki. If I make any myself, I will follow your instructions + I will fix the ";" issue right after doing some other things.

**Comment by smileycreations15** [comment]
@Nambaseking01 Well it is new 🌝

**Comment by Nambaseking01** [comment]
@smileycreations15 My website or your Wiki?

**Comment by smileycreations15** [comment]
@Nambaseking01 wiki

**Comment by smileycreations15** [comment]
@Nambaseking01 actually don't add tutorials bc it will be a different topic.

**Comment by Nambaseking01** [comment]
@smileycreations15 Okay!

**Comment by smileycreations15** [comment]
@Nambaseking01 u updated it 11s or a minute ago xd

**Comment by Nambaseking01** [comment]
@smileycreations15 Lol! ;P

**Comment by smileycreations15** [comment]
lol XD

**Comment by smileycreations15** [comment]
@Nambaseking01 Open this link: https://glitch.com/edit/#!/resolute-reaction , then click Sign In. Then click sign in with github :D

**Comment by Nambaseking01** [comment]
@smileycreations15 Okay!

**Comment by Nambaseking01** [comment]
I have a question. Should I make a good website advertising system for the adults activities section in the future where I can add this Wiki?

**Comment by smileycreations15** [comment]
@Nambaseking01 Yea!

**Comment by Nambaseking01** [comment]
Okay thanks!

**Comment by smileycreations15** [comment]
@Nambaseking01 I am making an advertising system.

**Comment by Nambaseking01** [comment]
Cool!

**Comment by smileycreations15** [comment]
:)

**Comment by Nambaseking01** [comment]
Am I allowed to use it for the advertising site?

**Comment by smileycreations15** [comment]
@Nambaseking01 yes

**Comment by Nambaseking01** [comment]
Thanks!

**Comment by smileycreations15** [comment]
@Nambaseking01 :)

**Comment by smileycreations15** [comment]
@Nambaseking01 code:

**Comment by Nambaseking01** [comment]
Code?

**Comment by Nambaseking01** [comment]
[REPOST] Code?

**Comment by smileycreations15** [comment]
@Nambaseking01 It displays random ads, who anyone can request. Are you sure?

**Comment by Nambaseking01** [comment]
Then... Just give the link to the website so I can see what it is like!

**Comment by smileycreations15** [comment]
@Nambaseking01 I am making a better system...

**Comment by Nambaseking01** [comment]
Okay!

**Comment by Nambaseking01** [comment]
> Add `[[Category:Scratch]]` at the end of each tutorial

**Comment by Nambaseking01** [comment]
Getting confused here... XD

**Comment by smileycreations15** [comment]
oof
